$(function() {
  var counter, selectors;
  selectors = ['.form__field input[type="text"]', '.form__field input[type="tel"]', '.form__field textarea'];
  $(document).on('ready focus blur', selectors.join(', '), function(e) {
    var $el;
    $el = $(this).parent('span');
    if ($el.length > 0) {
      $el.toggleClass('focused', $(this).is(':focus'));
    }
    return $el.toggleClass('has-text', $(this).val().length > 0);
  });
  $(document).on('click', '.button', function(e) {
    return $(this).siblings('input[type="submit"]').trigger('click');
  });
  counter = 0;
  return $(document).on('click', '.form__right input[type="submit"]', function(e) {
    e.preventDefault();
    $(this).parent().siblings('.wpcf7-response-output').slideUp(400);
    $(this).siblings('.ajax-loader').css({
      visibility: 'visible'
    });
    return window.setTimeout((function(_this) {
      return function() {
        counter++;
        if (counter < 2) {
          $(_this).parents('form').find('.form__field:nth-last-child(n+2) input').addClass('wpcf7-not-valid');
          $(_this).parent().siblings('.wpcf7-response-output').slideDown(400);
        } else {
          $('.wpcf7-not-valid').removeClass('wpcf7-not-valid');
          $(_this).parent().siblings('.wpcf7-good').slideDown(400);
          document.formsResponse();
        }
        return $(_this).siblings('.ajax-loader').css({
          visibility: 'hidden'
        });
      };
    })(this), 700 + Math.random() * (2000 - 700));
  });
});

// ---
// generated by coffee-script 1.9.2
